In [2]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd

# Corrected Raw URL
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

# Load CSV
titanic_train = pd.read_csv(url)

In [4]:
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
type(titanic_train)

pandas.core.frame.DataFrame

In [25]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [26]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [27]:
type(titanic_train['Age'])

pandas.core.series.Series

In [28]:
type(titanic_train[['Age']])

pandas.core.frame.DataFrame

In [29]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [30]:
titanic_train.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [32]:
titanic_train.dtypes[titanic_train.dtypes == 'object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [33]:
titanic_train.dtypes[titanic_train.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [35]:
titanic_train_Categorical =  titanic_train[titanic_train.dtypes[titanic_train.dtypes == 'object'].index]

In [36]:
titanic_train_Categorical.describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [37]:
titanic_train['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [40]:
age_null = np.where(titanic_train['Age'].isnull()==True)

In [42]:
titanic_train.iloc[age_null] # look index value

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [43]:
titanic_train['Fare'].max()

512.3292

In [44]:
titanic_train['Fare'] == max(titanic_train['Fare'])

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [47]:
high_fare_paid = np.where(titanic_train['Fare'] == max(titanic_train['Fare']))

In [51]:
titanic_train.iloc[high_fare_paid]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [52]:
titanic_train['Age'] == 24

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [53]:
age_24 = np.where(titanic_train['Age'] == 24)

In [58]:
titanic_train.iloc[age_24][['Name','Ticket','Age']]

,Name,Ticket,Age
89,"Celotti, Mr. Francesco",343275,24.0
118,"Baxter, Mr. Quigg Edmond",PC 17558,24.0
127,"Madsen, Mr. Fridtjof Arne",C 17369,24.0
139,"Giglio, Mr. Victor",PC 17593,24.0
142,"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...",STON/O2. 3101279,24.0
199,"Yrois, Miss. Henriette (""Mrs Harbeck"")",248747,24.0
210,"Ali, Mr. Ahmed",SOTON/O.Q. 3101311,24.0
234,"Leyson, Mr. Robert William Norman",C.A. 29566,24.0
247,"Hamalainen, Mrs. William (Anna)",250649,24.0
293,"Haas, Miss. Aloisia",349236,24.0
294,"Mineff, Mr. Ivan",349233,24.0
310,"Hays, Miss. Margaret Bechstein",11767,24.0
316,"Kantor, Mrs. Sinai (Miriam Sternin)",244367,24.0
341,"Fortune, Miss. Alice Elizabeth",19950,24.0
345,"Brown, Miss. Amelia ""Mildred""",248733,24.0
369,"Aubart, Mme. Leontine Pauline",PC 17477,24.0
394,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",PP 9549,24.0
437,"Richards, Mrs. Sidney (Emily Hocking)",29106,24.0
499,"Svensson, Mr. Olof",350035,24.0
514,"Coleff, Mr. Satio",349209,24.0
565,"Davies, Mr. Alfred J",A/4 48871,24.0
600,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",243847,24.0
615,"Herman, Miss. Alice",220845,24.0
641,"Sagesser, Mlle. Emma",PC 17477,24.0
655,"Hickman, Mr. Leonard Mark",S.O.C. 14879,24.0
710,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",PC 17482,24.0
743,"McNamee, Mr. Neal",376566,24.0
770,"Lievens, Mr. Rene Aime",345781,24.0
858,"Baclini, Mrs. Solomon (Latifa Qurban)",2666,24.0
864,"Gill, Mr. John William",233866,24.0

In [5]:
titanic_train['Cabin'].isnull() == True

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: Cabin, Length: 891, dtype: bool

In [6]:
cabin_null = np.where(titanic_train['Cabin'].isnull()==True)

In [7]:
cabin_null

(array([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,  15,  16,  17,
         18,  19,  20,  22,  24,  25,  26,  28,  29,  30,  32,  33,  34,
         35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
         48,  49,  50,  51,  53,  56,  57,  58,  59,  60,  63,  64,  65,
         67,  68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,  80,
         81,  82,  83,  84,  85,  86,  87,  89,  90,  91,  93,  94,  95,
         98,  99, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112,
        113, 114, 115, 116, 117, 119, 120, 121, 122, 125, 126, 127, 129,
        130, 131, 132, 133, 134, 135, 138, 140, 141, 142, 143, 144, 145,
        146, 147, 149, 150, 152, 153, 154, 155, 156, 157, 158, 159, 160,
        161, 162, 163, 164, 165, 167, 168, 169, 171, 172, 173, 175, 176,
        178, 179, 180, 181, 182, 184, 186, 187, 188, 189, 190, 191, 192,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 206, 207, 208, 210,
        211, 212, 213, 214, 216, 217, 219, 220, 221, 222, 223, 225, 226,
        227, 228, 229, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
        241, 242, 243, 244, 246, 247, 249, 250, 253, 254, 255, 256, 258,
        259, 260, 261, 264, 265, 266, 267, 270, 271, 272, 274, 276, 277,
        278, 279, 280, 281, 282, 283, 285, 286, 287, 288, 289, 290, 293,
        294, 295, 296, 300, 301, 302, 304, 306, 308, 312, 313, 314, 315,
        316, 317, 320, 321, 322, 323, 324, 326, 328, 330, 333, 334, 335,
        338, 342, 343, 344, 346, 347, 348, 349, 350, 352, 353, 354, 355,
        357, 358, 359, 360, 361, 362, 363, 364, 365, 367, 368, 371, 372,
        373, 374, 375, 376, 378, 379, 380, 381, 382, 383, 384, 385, 386,
        387, 388, 389, 391, 392, 395, 396, 397, 398, 399, 400, 401, 402,
        403, 404, 405, 406, 407, 408, 409, 410, 411, 413, 414, 415, 416,
        417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 431,
        432, 433, 436, 437, 439, 440, 441, 442, 443, 444, 446, 447, 448,
        450, 451, 454, 455, 458, 459, 461, 463, 464, 465, 466, 467, 468,
        469, 470, 471, 472, 474, 476, 477, 478, 479, 480, 481, 482, 483,
        485, 488, 489, 490, 491, 493, 494, 495, 497, 499, 500, 501, 502,
        503, 506, 507, 508, 509, 510, 511, 513, 514, 517, 518, 519, 521,
        522, 524, 525, 526, 528, 529, 530, 531, 532, 533, 534, 535, 537,
        538, 541, 542, 543, 545, 546, 547, 548, 549, 551, 552, 553, 554,
        555, 557, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
        570, 573, 574, 575, 576, 578, 579, 580, 582, 584, 586, 588, 589,
        590, 592, 593, 594, 595, 596, 597, 598, 600, 601, 602, 603, 604,
        605, 606, 607, 608, 610, 611, 612, 613, 614, 615, 616, 617, 619,
        620, 622, 623, 624, 626, 628, 629, 631, 633, 634, 635, 636, 637,
        638, 639, 640, 642, 643, 644, 646, 648, 649, 650, 651, 652, 653,
        654, 655, 656, 657, 658, 660, 661, 663, 664, 665, 666, 667, 668,
        670, 672, 673, 674, 675, 676, 677, 678, 680, 682, 683, 684, 685,
        686, 687, 688, 691, 692, 693, 694, 695, 696, 697, 702, 703, 704,
        705, 706, 708, 709, 713, 714, 718, 719, 720, 721, 722, 723, 725,
        726, 727, 728, 729, 731, 732, 733, 734, 735, 736, 738, 739, 743,
        744, 746, 747, 749, 750, 752, 753, 754, 755, 756, 757, 758, 760,
        761, 762, 764, 766, 767, 768, 769, 770, 771, 773, 774, 775, 777,
        778, 780, 783, 784, 785, 786, 787, 788, 790, 791, 792, 793, 794,
        795, 797, 798, 799, 800, 801, 803, 804, 805, 807, 808, 810, 811,
        812, 813, 814, 816, 817, 818, 819, 821, 822, 824, 825, 826, 827,
        828, 830, 831, 832, 833, 834, 836, 837, 838, 840, 841, 842, 843,
        844, 845, 846, 847, 848, 850, 851, 852, 854, 855, 856, 858, 859,
        860, 861, 863, 864, 865, 866, 868, 869, 870, 873, 874, 875, 876,
        877, 878, 880, 881, 882, 883, 884, 885, 886, 888, 890], dtype=int64),)

In [8]:
titanic_train.iloc[cabin_null]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [15]:
# male passengers who surived
survived_males = titanic_train[(titanic_train['Survived'] == 1) & (titanic_train['Sex'] == 'male')]

In [17]:
survived_males[['Age','Name']]

      Age                             Name
17    NaN     Williams, Mr. Charles Eugene
21   34.0            Beesley, Mr. Lawrence
23   28.0     Sloper, Mr. William Thompson
36    NaN                 Mamee, Mr. Hanna
55    NaN                Woolner, Mr. Hugh
..    ...                              ...
838  32.0                  Chip, Mr. Chang
839   NaN             Marechal, Mr. Pierre
857  51.0           Daly, Mr. Peter Denis
869   4.0  Johnson, Master. Harold Theodor
889  26.0            Behr, Mr. Karl Howell

[109 rows x 2 columns]

In [18]:
titanic_train['new_col'] = 'Pravin'

In [19]:
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Pravin
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Pravin
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Pravin
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Pravin
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Pravin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Pravin
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Pravin
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Pravin
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Pravin
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Pravin

In [20]:
l = [1,2,3,4,5]

In [21]:
pd.Series(l)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [25]:
pd.DataFrame(l)

   0
0  1
1  2
2  3
3  4
4  5

.loc => use when user definded indexed present
.iloc => use when pre build indexs present

In [27]:
df6 = pd.DataFrame(np.random.randint(3,6,(4,5)), index = ['a','b','c','d'], columns = ['x','y','z','u','v'])

In [28]:
df6

   x  y  z  u  v
a  5  4  4  4  3
b  3  3  3  5  5
c  4  3  4  5  4
d  4  5  4  4  3

In [30]:
df6.loc[['c','d'],['z','u']]

   z  u
c  4  5
d  4  4

In [32]:
df6['new'] = df6['x'] = df6.y

In [33]:
df6.drop('x')

KeyError: "['x'] not found in axis"

In [34]:
df6.drop('x',axis=1,inplace=True) #columns

In [35]:
df6

   y  z  u  v  new
a  4  4  4  3    4
b  3  3  5  5    3
c  3  4  5  4    3
d  5  4  4  3    5

In [37]:
df6.drop('a') #row

   y  z  u  v  new
b  3  3  5  5    3
c  3  4  5  4    3
d  5  4  4  3    5

In [42]:
np.random.seed(23)
df = pd.DataFrame(np.random.randn(4,5),index = ['a','b','c','d'],columns=['x','y','z','u','v'])

In [43]:
df

          x         y         z         u         v
a  0.666988  0.025813 -0.777619  0.948634  0.701672
b -1.051082 -0.367548 -1.137460 -1.322148  1.772258
c -0.347459  0.670140  0.322272  0.060343 -1.043450
d -1.009942  0.441736  1.128877 -1.838068 -0.938769

In [44]:
df[df<0]

          x         y         z         u         v
a       NaN       NaN -0.777619       NaN       NaN
b -1.051082 -0.367548 -1.137460 -1.322148       NaN
c -0.347459       NaN       NaN       NaN -1.043450
d -1.009942       NaN       NaN -1.838068 -0.938769

In [46]:
neg_values = df.values[df.values<0]

In [47]:
neg_values

array([-0.77761941, -1.05108156, -0.36754812, -1.13745969, -1.32214752,
       -0.34745899, -1.04345   , -1.00994188, -1.83806777, -0.93876863])

In [57]:
c = neg_values

for i in df.columns:
    for j in df.index:
        if df[i][j] in c:
            print(i,j,df[i][j])

x b -1.0510815639071178
x c -0.34745899102186334
x d -1.0099418765878465
y b -0.3675481161171661
z a -0.7776194131918178
z b -1.1374596907250272
u b -1.3221475225908594
u d -1.8380677677579502
v c -1.0434500017467254
v d -0.9387686311201282

In [58]:
d = {'key1':[1,2,3,4,np.nan],"key2":["pravin",'ganesh',4,5,6],'key3':[np.nan,np.nan,np.nan,3,8]}
df = pd.DataFrame(d)

In [59]:
df

   key1    key2  key3
0   1.0  pravin   NaN
1   2.0  ganesh   NaN
2   3.0       4   NaN
3   4.0       5   3.0
4   NaN       6   8.0

In [60]:
df.dropna()

   key1 key2  key3
3   4.0    5   3.0

In [61]:
df.fillna(-1)

   key1    key2  key3
0   1.0  pravin  -1.0
1   2.0  ganesh  -1.0
2   3.0       4  -1.0
3   4.0       5   3.0
4  -1.0       6   8.0

In [62]:
df.fillna(value=df['key1'].mean())

   key1    key2  key3
0   1.0  pravin   2.5
1   2.0  ganesh   2.5
2   3.0       4   2.5
3   4.0       5   3.0
4   2.5       6   8.0

In [63]:
df

   key1    key2  key3
0   1.0  pravin   NaN
1   2.0  ganesh   NaN
2   3.0       4   NaN
3   4.0       5   3.0
4   NaN       6   8.0

In [64]:
employees = {
    "name": ["Alice", "Bob", "Charlie", "Alice", "David"],
    "mail_id": ["alice@example.com", "bob@example.com", "charlie@example.com", "alice@example.com", "david@example.com"],
    "salary": [50000, 60000, 55000, 50000, 62000]
}

df = pd.DataFrame(employees)

In [65]:
df

      name              mail_id  salary
0    Alice    alice@example.com   50000
1      Bob      bob@example.com   60000
2  Charlie  charlie@example.com   55000
3    Alice    alice@example.com   50000
4    David    david@example.com   62000

In [66]:
df.groupby('name')

In [71]:
df.groupby('mail_id')['salary'].mean()

mail_id
alice@example.com      50000.0
bob@example.com        60000.0
charlie@example.com    55000.0
david@example.com      62000.0
Name: salary, dtype: float64

In [72]:
df.groupby('name')['salary'].sum()

name
Alice      100000
Bob         60000
Charlie     55000
David       62000
Name: salary, dtype: int64

In [73]:
df.groupby('mail_id').describe()

                    salary                                                    \
                     count     mean  std      min      25%      50%      75%
mail_id
alice@example.com      2.0  50000.0  0.0  50000.0  50000.0  50000.0  50000.0
bob@example.com        1.0  60000.0  NaN  60000.0  60000.0  60000.0  60000.0
charlie@example.com    1.0  55000.0  NaN  55000.0  55000.0  55000.0  55000.0
david@example.com      1.0  62000.0  NaN  62000.0  62000.0  62000.0  62000.0


                         max
mail_id
alice@example.com    50000.0
bob@example.com      60000.0
charlie@example.com  55000.0
david@example.com    62000.0

In [74]:
df.groupby('mail_id').describe().loc['charlie@example.com']

salary  count        1.0
        mean     55000.0
        std          NaN
        min      55000.0
        25%      55000.0
        50%      55000.0
        75%      55000.0
        max      55000.0
Name: charlie@example.com, dtype: float64

In [77]:
df.groupby('mail_id').describe().loc['charlie@example.com']['salary']['mean']

55000.0

In [79]:
df.groupby('mail_id').describe().T # convert row into col

mail_id       alice@example.com  bob@example.com  charlie@example.com  \
salary count                2.0              1.0                  1.0
       mean             50000.0          60000.0              55000.0
       std                  0.0              NaN                  NaN
       min              50000.0          60000.0              55000.0
       25%              50000.0          60000.0              55000.0
       50%              50000.0          60000.0              55000.0
       75%              50000.0          60000.0              55000.0
       max              50000.0          60000.0              55000.0

mail_id       david@example.com
salary count                1.0
       mean             62000.0
       std                  NaN
       min              62000.0
       25%              62000.0
       50%              62000.0
       75%              62000.0
       max              62000.0